"""books and handoff_events

Revision ID: e0908d2ceebb
Revises: 0eda05da4d84
Create Date: 2026-09-11 19:01:54.527596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0908d2ceebb'
down_revision: Union[str, None] = '0eda05da4d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('genre', sa.String(length=60), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('chooser_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), server_default='circulating', nullable=False),
    sa.Column('current_holder_user_id', sa.Integer(), nullable=True),
    sa.Column('current_page', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chooser_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_holder_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_group_id'), 'books', ['group_id'], unique=False)
    op.create_table('handoff_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('page_at_handoff', sa.Integer(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handoff_events_book_id'), 'handoff_events', ['book_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_handoff_events_book_id'), table_name='handoff_events')
    op.drop_table('handoff_events')
    op.drop_index(op.f('ix_books_group_id'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
